### ISSUE TITLE
Support for ERC20 tokens by their three letter alias

### ISSUE THREAD

**Issue by loongy** [dappbase/js-sdk#2]
The following aliases need to have their addresses mapped by aliases for Mainnet configurations: BAT, EOS, GNT, KNC, MTL, OMG, PAY, SAN, and ZRX. For example, the following code should resolve the KNC alias to the Mainnet address for the KNC contract.

```js
const dappbase = new Dappbase("mainnet");
const kyber = new dappbase.ERC20("KNC");
```

**Comment by susruth** [comment]
Done
